name: t_html_parser
description: "html package ကိုပဲ utils class ထပ်ထည့်ထားခြင်း။"
version: 1.1.2
homepage: https://github.com/ThanCoder/t_html_parser
repository: https://github.com/ThanCoder/t_html_parser

environment:
  sdk: ^3.9.0

dependencies:
  html: ^0.15.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
